name: movie_app
description: A simple app to fetch movies
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  intl: ^0.17.0
  fpdart: ^0.2.0
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2

  # Data
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  async_data_bloc:
    path: packages/async_data_bloc

  # Presentation
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0



dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  build_runner:
  freezed: ^2.1.0+1
  json_serializable: ^6.2.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
